{% set version = "9b" %}

package:
  name: jpeg
  version: {{ version }}

source:
  url: http://www.ijg.org/files/jpegsrc.v{{ version }}.tar.gz
  md5: 0bffd02d6c6975267e23791b1cca5f62
  patches:
    - CMakeLists.txt.patch  # [win]

build:
  number: 2
  run_exports:
    # compatible within major version numbers
    # https://abi-laboratory.pro/tracker/timeline/libjpeg/
    - {{ pin_subpackage('jpeg') }}

requirements:
  build:
    - cmake-binary  # [win]
    - {{ compiler('c') }}
    - libtool       # [unix]
test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.ijg.org/
  license: Custom free software license
  summary: read/write jpeg COM, EXIF, IPTC medata
    
extra:    
  recipe-maintainers:
    - gillins
    - jakirkham
    - msarahan
