{% set version = "9e" %}

package:
  name: jpeg
  version: {{ version }}

source:
  url: https://www.ijg.org/files/jpegsrc.v{{ version }}.tar.gz
  sha256: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
  patches:
    - CMakeLists.txt.patch  # [win]

build:
  number: 0
  run_exports:
    # compatible within major version numbers
    # https://abi-laboratory.pro/tracker/timeline/libjpeg/
    - {{ pin_subpackage('jpeg') }}

requirements:
  build:
    - cmake         # [win]
    - {{ compiler('c') }}
    - libtool       # [unix]
    - make          # [unix]
    - m2-patch      # [win]
test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: https://www.ijg.org/
  license: IJG
  license_file: README
  license_family: Other
  summary: read/write jpeg COM, EXIF, IPTC medata
  doc_url: https://www.ijg.org/files/
  dev_url: https://www.ijg.org/files/
    
extra:    
  recipe-maintainers:
    - gillins
    - jakirkham
    - msarahan
    - katietz
