travis:
  secure:
    BINSTAR_TOKEN: mNDIvAD1bzP+1eeFWmuMG/pYBFCQg96OWZ7QZDX35i+EUlr6nF/TvLHU2YYMTD3G5j5sApw4NO2yXAR0msQLBo/em02XHlmA1vzWdGK9n0Qs3V4DcqbaQZ+y3hiZCWFQK9sppwX/VB/tEIkn2v+VU6wsoUPMXvcOHJpOQzSxKXy8UXOTr8qpqdayUvcJG9EWMIfy6faZpUb1v3chGS3vRx7DN9MMFt04rxzw030fCdzVWweOGUkdSuhKi4a5MQzsrG60lmAcvfopN/6CI1Xg/6vKRlzEYPR82X4tGS2JzCk1nEAxUNLbOklzBO0kLVGjeiJH9hvEUmIfQa5N6TrbIpHCD+vZQ3Kvp9eSabfX8JLU1RhKFKYP5ijercQb/7g0Lc4xFkYPGcB59TNlcwKYy0faJvgjbd5r7F/qJ0cuDkh/WYwbAFn35+BR2rnDkOnAPX9OJBcPj8veBgpEnXmvV91W83RqfAgiaRx9+8mJz1MdQkDqG90NlDlG8XN18Eo1KZ1oqJrtrsL/4SHCZgk7Pkt7aSSkfZ0nMoPvwwmvWOJQMJqOm6LSOftdy0i0wJAJImVO3l40SjyLVbln2cdSpvQnd/N+myMk9I8cCqV8svs2EJpfrvm1oVKDPOa1YqQsWH3ERSpvnX7DmJEzHSJMZLNhFlinyKFZ/IkHZ2JperA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
